services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/home/laravel/app
        networks:
            - laravel

    nginx:
        image: nginx:1.25
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/home/laravel/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
